### ISSUE TITLE
PHP Fatal error

### ISSUE THREAD

**Issue by manuelge** [etruel/wpematico-custom-hooks#7]
Cuando se intenta guardar un código en cualquier filtro del custom hooks ocurre un fatal error durante el chequeo de error de la sintaxis.

PHP Fatal error:  Uncaught Error: Cannot use object of type WP_Error as array in /var/www/clients/client1/web58/web/wp-content/plugins/wpematico-custom-hooks/includes/wpematicohk_sintax.php:49
Stack trace:
#0 /var/www/clients/client1/web58/web/wp-includes/class-wp-hook.php(308): wpematicohk_sintax::ajax_callback()
#1 /var/www/clients/client1/web58/web/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
#2 /var/www/clients/client1/web58/web/wp-includes/plugin.php(517): WP_Hook->do_action()
#3 /var/www/clients/client1/web58/web/wp-admin/admin-ajax.php(188): do_action()
#4 {main}
  thrown in /var/www/clients/client1/web58/web/wp-content/plugins/wpematico-custom-hooks/includes/wpematicohk_sintax.php on line 49

**Comment by manuelge** [comment]
El mismo error continua
